### PR TITLE
Fix vlcradio setup.sh to support raspbian buster

### PR DESCRIPTION
**Pull request by mstahel**
- added buster to supported releases
- added seperate pkgdeplist for buster as vlc-nox is gone

### CODE REVIEW

**Comment by mstahel** [comment]
Fixes #25

**Comment by Gadgetoid** [comment]
Super appreciated- thank you!

**Comment by Gadgetoid** [comment]
That's odd- the `vlcradio` script should clone this repository at master, and the change is definitely there:

https://github.com/pimoroni/phat-beat/blob/cd860143e5d84e78e1ef81589d8f461ce34a4ea3/projects/vlc-radio/setup.sh#L203-L204

Where's your paste of `setup.sh` coming from?

**Comment by bobrathbone** [comment]
Hi Philip,

 

curl https://get.pimoroni.com/vlcradio | bash

 

The above instruction comes from page 87 of my Internet radio project at https://bobrathbone.com/raspberrypi/documents/Raspberry%20PI%20Radio.pdf and is still available from get.pimoroni.com.

This instruction previously came from Pimoroni documentation, probably on GitHub. 

 

Upon further investigation I now see that this has changed to:

 

curl https://get.pimoroni.com/phatbeat | bash

from instructions https://github.com/pimoroni/phat-beat#full-install-recommended 

 

I have now retested using the new script and the installation now works fine.

I will update my documentation and issue #26 shortly

 

My apologies for any inconvenience.

 

Regards

Bob

 

Bob Rathbone

 

Website: http://www.bobrathbone.com

Email: bob@bobrathbone.com

 

lpic2-logo-small

**Comment by bobrathbone** [comment]
So which script should I be using?
curl https://get.pimoroni.com/vlcradio | bash
or
curl https://get.pimoroni.com/phatbeat | bash

**Comment by Gadgetoid** [comment]
It depends what you want to accomplish-

`vlcradio` installs a whole plethora of software and configuration designed to get your Pi up and running as a radio using pHAT  BEAT and the VLC music player.

`phat-beat` - if I recall correctly - just installs the python library and adds `dtoverlay=hifiberry-dac` to your `/boot/config.txt` - ie: gets the product up and running for you to write your own code.

**Pull request merged**
